import 'package:freezed_annotation/freezed_annotation.dart';

part 'tasks_data.freezed.dart';
part 'tasks_data.g.dart';

@freezed

/// Task class autogenerated by freezed
class Task with _$Task {
  const factory Task({
    required String description,
    required bool isDone,
  }) = _Task;

/// get Task from json
  factory Task.fromJson(Map<String, Object?> json) => _$TaskFromJson(json);
}